# Numpy

Материалы:
* Макрушин С.В. "Лекция 1: Библиотека Numpy"
* https://numpy.org/doc/stable/user/index.html
* https://numpy.org/doc/stable/reference/index.html

## Задачи для совместного разбора

1. Сгенерировать двухмерный массив `arr` размерности (4, 7), состоящий из случайных действительных чисел, равномерно распределенных в диапазоне от 0 до 20. Нормализовать значения массива с помощью преобразования вида  $𝑎𝑥+𝑏$  так, что после нормализации максимальный элемент масcива будет равен 1.0, минимальный 0.0

In [12]:
import numpy as np
from sympy import *
from random import *
init_printing()
a = np.array([[randint(0,20) for i in range(4)] for j in range(7)])
(a - np.min(a))/(np.max(a) - np.min(a))
#a/np.linalg.norm(a)
            
        

array([[0.89473684, 0.10526316, 0.26315789, 0.26315789],
       [0.78947368, 0.42105263, 0.84210526, 0.05263158],
       [0.78947368, 0.47368421, 0.        , 0.78947368],
       [0.31578947, 0.73684211, 0.63157895, 1.        ],
       [0.42105263, 0.31578947, 0.26315789, 0.84210526],
       [0.63157895, 0.31578947, 0.15789474, 0.68421053],
       [0.89473684, 0.31578947, 0.26315789, 0.94736842]])

2. Создать матрицу 8 на 10 из случайных целых (используя модуль `numpy.random`) чисел из диапозона от 0 до 10 и найти в ней строку (ее индекс и вывести саму строку), в которой сумма значений минимальна.

In [3]:
Matrix = np.array([[randint(0,10) for i in range(8)] for j in range(10)])
Matrix


array([[10,  0,  0,  1,  4,  2,  4,  2],
       [ 7,  5,  2,  6,  8,  0,  6, 10],
       [ 7,  9, 10,  0,  3,  2,  6,  4],
       [ 4,  3,  5,  4, 10,  9,  1,  5],
       [ 5,  7,  2,  8, 10,  4,  1,  7],
       [ 9,  3,  5,  4,  4,  3,  4,  6],
       [ 1,  1,  6,  0,  9,  4,  1,  1],
       [ 4,  0,  6,  4, 10,  8,  3,  6],
       [ 3,  9,  0,  1,  0,  3,  8,  9],
       [ 6,  6,  0,  4,  1,  5,  6,  6]])

In [4]:
MIN = 100000000000000000000
for i in range(len(Matrix)):
    if sum(Matrix[i])<MIN: 
        MIN, k, t = sum(Matrix[i]), Matrix[i], i
k,t

(array([10,  0,  0,  1,  4,  2,  4,  2]), 0)

3. Найти евклидово расстояние между двумя одномерными векторами одинаковой размерности.

In [5]:
a = np.random.randint(10,size = (1,20))
b = np.random.randint(10,size = (1,20))
r = np.linalg.norm(a-b)
r

4. Решить матричное уравнение `A*X*B=-C` - найти матрицу `X`. Где `A = [[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]]`, `B=[[3, -1], [2, 1]]`, `C=[[7, 21], [11, 8], [8, 4]]`.

In [15]:
A = np.array(([[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]]))
B = np.array(([[3, -1], [2, 1]]))
C = np.array(([[7, 21], [11, 8], [8, 4]]))
AX = (C*(-1) @ np.linalg.inv(B))
X = (np.linalg.inv(A) @ AX)
print(np.around(X, decimals = 2))


[[ 1.  0.]
 [-2.  1.]
 [ 3. -4.]]


## Лабораторная работа №1

Замечание: при решении данных задач не подразумевается использования циклов или генераторов Python, если в задании не сказано обратного. Решение должно опираться на использования функционала библиотеки `numpy`.

1. Файл `minutes_n_ingredients.csv` содержит информацию об идентификаторе рецепта, времени его выполнения в минутах и количестве необходимых ингредиентов. Считайте данные из этого файла в виде массива `numpy` типа `int32`, используя `np.loadtxt`. Выведите на экран первые 5 строк массива.

In [40]:
import numpy as np
faile = np.loadtxt('minutes_n_ingredients.csv', delimiter=',', dtype='int32', skiprows = 1)
print(faile[:5])

[[127244     60     16]
 [ 23891     25      7]
 [ 94746     10      6]
 [ 67660      5      6]
 [157911     60     14]]


2. Вычислите среднее значение, минимум, максимум и медиану по каждому из столбцов, кроме первого.

In [41]:
print('Сред значение ', np.mean(faile[:,1:],0))
print('Мин значения ',np.min(faile[:,1:],0))
print('Макс значения ',np.max(faile[:,1:],0))
print('Медианы ',np.median(faile[:,1:],0))

Сред значение  [2.16010017e+04 9.05528000e+00]
Мин значения  [0 1]
Макс значения  [2147483647         39]
Медианы  [40.  9.]


3. Ограничьте сверху значения продолжительности выполнения рецепта значением квантиля $q_{0.75}$. 

In [49]:
Max = np.quantile(faile[:,1], 0.75, axis = 0)
print(maxim)
print(faile[faile[:,1]<=Max])


65.0
[[127244     60     16]
 [ 23891     25      7]
 [ 94746     10      6]
 ...
 [ 43407     35      7]
 [498432     65     15]
 [370915      5      4]]


4. Посчитайте, для скольких рецептов указана продолжительность, равная нулю. Замените для таких строк значение в данном столбце на 1.

In [48]:
a = np.count_nonzero(faile[:,1] == 0)
faile[faile[:,1]==0] = 1
print( np.count_nonzero(faile[:,1] == 0))

0


5. Посчитайте, сколько уникальных рецептов находится в датасете.

In [50]:
a = np.unique(faile[:,0])
print(len(a))

99522


6. Сколько и каких различных значений кол-ва ингредиентов присутвует в рецептах из датасета?

In [51]:
a, num = np.unique(faile[:,2], return_counts=True)
print(np.column_stack((a, num)))

[[    1   492]
 [    2   924]
 [    3  2884]
 [    4  5479]
 [    5  7874]
 [    6  9328]
 [    7 10579]
 [    8 10887]
 [    9 10542]
 [   10  9548]
 [   11  8262]
 [   12  6574]
 [   13  4985]
 [   14  3639]
 [   15  2583]
 [   16  1760]
 [   17  1237]
 [   18   787]
 [   19   566]
 [   20   376]
 [   21   214]
 [   22   161]
 [   23   105]
 [   24    68]
 [   25    50]
 [   26    28]
 [   27    16]
 [   28    16]
 [   29    12]
 [   30    12]
 [   31     3]
 [   32     1]
 [   33     2]
 [   34     1]
 [   35     3]
 [   37     1]
 [   39     1]]


7. Создайте версию массива, содержащую информацию только о рецептах, состоящих не более чем из 5 ингредиентов.

In [55]:
arr = faile[faile[:,2]<=5]
a = np.copy(arr)
print(a)
print('\n\n',faile)

[[446597     15      5]
 [204134      5      3]
 [ 25623      6      4]
 ...
 [ 52088     60      5]
 [128811     15      4]
 [370915      5      4]]


 [[127244     60     16]
 [ 23891     25      7]
 [ 94746     10      6]
 ...
 [498432     65     15]
 [370915      5      4]
 [ 81993    140     14]]


8. Для каждого рецепта посчитайте, сколько в среднем ингредиентов приходится на одну минуту рецепта. Найдите максимальное значение этой величины для всего датасета

In [57]:
a = faile[:,2]/faile[:,1]
print(max(a))

23.0


9. Вычислите среднее количество ингредиентов для топ-100 рецептов с наибольшей продолжительностью

In [58]:
a = faile[:,1].argsort()
b = faile[a][-100:]
print(np.mean(b[:,2], axis = 0))

6.61


10. Выберите случайным образом и выведите информацию о 10 различных рецептах

In [59]:
a = np.random.randint(faile.shape[0], size = 10)
print(faile[a])

[[203854      8      3]
 [  4114     15      7]
 [406258     45      8]
 [193195     63     16]
 [ 42352     55     12]
 [ 76655     18      6]
 [143913    330     18]
 [491647     60      7]
 [188015     55     10]
 [289521     75     10]]


11. Выведите процент рецептов, кол-во ингредиентов в которых меньше среднего.

In [60]:
a = np.mean(faile[:,2], axis = 0)
print(faile[faile[:,2]<a])
print('----')
print((100*len(faile[faile[:,2]<a]))/len(faile))

[[ 23891     25      7]
 [ 94746     10      6]
 [ 67660      5      6]
 ...
 [371794     35      8]
 [ 43407     35      7]
 [370915      5      4]]
----
58.989


12. Назовем "простым" такой рецепт, длительность выполнения которого не больше 20 минут и кол-во ингредиентов в котором не больше 5. Создайте версию датасета с дополнительным столбцом, значениями которого являются 1, если рецепт простой, и 0 в противном случае.

In [61]:
a = np.append(faile, np.zeros((faile.shape[0],1), dtype = 'int32'), axis = 1)
a[np.logical_and(a[:,1]<=20,a[:,2]<=5)] = 1
a = a.copy()
print(a)

[[127244     60     16      0]
 [ 23891     25      7      0]
 [ 94746     10      6      0]
 ...
 [498432     65     15      0]
 [     1      1      1      1]
 [ 81993    140     14      0]]


13. Выведите процент "простых" рецептов в датасете

In [62]:
b = a[a[:,3] == 1]
print((100*len(b)/len(faile)))

9.943


14. Разделим рецепты на группы по следующему правилу. Назовем рецепты короткими, если их продолжительность составляет менее 10 минут; стандартными, если их продолжительность составляет более 10, но менее 20 минут; и длинными, если их продолжительность составляет не менее 20 минут. Создайте трехмерный массив, где нулевая ось отвечает за номер группы (короткий, стандартный или длинный рецепт), первая ось - за сам рецепт и вторая ось - за характеристики рецепта. Выберите максимальное количество рецептов из каждой группы таким образом, чтобы было возможно сформировать трехмерный массив. Выведите форму полученного массива.

In [64]:
a1 = faile[faile[:,1]<10]
a2 = faile[np.logical_and(faile[:,1]>=10, faile[:,1]<20)]
a3 = faile[faile[:,1]>=20]
maxim = min(len(a1), len(a2), len(a3))
b = np.array([[a1[:maxim-1],a2[:maxim-1],a3[:maxim-1]]])
print(b)

[[[[ 67660      5      6]
   [366174      7      9]
   [204134      5      3]
   ...
   [     1      1      1]
   [420725      5      3]
   [     1      1      1]]

  [[ 94746     10      6]
   [ 33941     18      9]
   [446597     15      5]
   ...
   [107094     10      4]
   [  9831     15      7]
   [335859     12     14]]

  [[127244     60     16]
   [ 23891     25      7]
   [157911     60     14]
   ...
   [ 92137     80      9]
   [168901     25      7]
   [392339     35     13]]]]
